services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: saasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d saasdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
    container_name: backend-app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres-db    
      POSTGRES_PORT: 5432          
      POSTGRES_DB: saasdb       
      POSTGRES_USER: postgres     
      POSTGRES_PASSWORD: postgres  
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - backend-network
    restart: on-failure

volumes:
  postgres_data:

networks:
  backend-network: